// psuperscript
function psuperscript(selectid)
{
   let inputbox = document.getElementById(selectid);
   document.getElementById(selectid+'p').innerHTML = inputbox.placeholder;
}

// updateP4DropDown
function updateP4DropDown(selectid)
{
   let dropdown = document.getElementById(selectid);
   let val = "";
   for (let i=0; i<dropdown.options.length; i++)
   {
      if (dropdown.options[i].selected)
      {
         if (val.length)
            val += ", "
         val += dropdown.options[i].value;
      }
   }
   document.getElementById(selectid+'p').innerHTML = val;
}

// stringAddFiller
function stringAddFiller (str)
{
   return (str.replace(/ /g,'_'));
}  

// topicsDynamicUpdate
function topicsDynamicUpdate(purpose)
{
   updateP4DropDown("topics");
   populateSubDropDown ("topics", purpose);
}

// populateSubDropDown
function populateSubDropDown(selectid, purpose)
{
   let optionsMap = 
   {
      Accomplishments :[ "Been complimented",
            "Come up with a new idea that improved things",
            "Developed or implemented new procedures or systems",
            "Helped Others",
            "Identified a problem and solved it",
            "Increased revenue or sales",
            "Re-organized something to make it work better",
            "Received awards",
            "Saved money",
            "Saved time",
            "Worked on special projects",
            "Others"],
      Body_Building : [ "Barbell Curl",
            "Bench Press",
            "Bent-over Row",
            "Bodybuilding Training Splits",
            "Cardio",
            "Deadlift",
            "Diet",
            "Dietary Supplementation",
            "Dumbbell Lateral Raise",
            "Exercise Selection",
            "Health",
            "Muscle",
            "Overhead Press",
            "Protein",
            "Resistance Band Raise",
            "Squat",
            "Weight Training",
            "Others"],
      Books : [ "Authors",
            "Autobiographies",
            "Biographies",
            "Book Clubs",
            "Book Recommendations",
            "Childrens Books",
            "Classics",
            "Comics",
            "Fans of a Particular Series",
            "Favorite Authors",
            "Fictional",
            "Movies Inspired from Books",
            "Murder Mystery",
            "Mythological Books",
            "Non-Classics",
            "Non-Fictional",
            "Poetry",
            "Poets",
            "Romantic Novels",
            "Science Fiction",
            "Self-help Books",
            "Story Books",
            "Suspense Thrillers",
            "Technical Journals",
            "Writing Books",
            "Others"],
      Bucket_List :[ "African Safari",
            "Get Married",
            "Go Parasailing",
            "Go to College",
            "Swim with Dolphins",
            "Travel around the World",
            "Travel",
            "Visit other Country",
            "Others" ],
      Career_Choices : [ "Administration",
            "Business",
            "Cybersecurity",
            "Data Science",
            "Digital Marketing",
            "Doctor",
            "Education",
            "Engineer",
            "Finance",
            "HR",
            "Management",
            "Marketing",
            "Nurse",
            "Pilot",
            "Sales",
            "Software",
            "Teacher",
            "Others"],
      Clothes :[ "Accessories",
            "Fashion",
            "Kidswear",
            "Modern",
            "Partywear",
            "Sewing",
            "Shopping",
            "Traditional",
            "Others"],
      Cooking : [ "Appetizers",
            "Baby Food",
            "Baking for Fun",
            "Baking for Kids",
            "Baking",
            "Beef",
            "Breakfast Ideas",
            "Cake Decoration",
            "Chicken",
            "Cooking Classes",
            "Cooking Techniques",
            "Cooking for Fun",
            "Desserts",
            "Dinner Ideas",
            "Festivals",
            "Fish",
            "Healthy Cooking",
            "Lunch Ideas",
            "Lunchbox Ideas",
            "Parties",
            "Pastries",
            "Pork",
            "Presentation",
            "Seafood",
            "Specific Cusine",
            "Sweets",
            "Thankgs Giving Meal",
            "Vegan",
            "Vegetarian Cooking",
            "Others" ],
      Current_Trends :[ "AI and Machine Learning",
            "Advancements in Technology",
            "Biotechnology and Genomics",
            "Climate Change",
            "Cybersecurity and Data Privacy",
            "Demographic Shifts",
            "Digital Currency",
            "Education and EdTech",
            "Entertainment and Streaming",
            "Fashion Trends",
            "Food Security",
            "Geopolitical Events",
            "Healthcare Innovation",
            "Mental Health Awareness",
            "Nuclear Fusion",
            "Public Health",
            "Renewable Energy",
            "Social Issues",
            "Space Exploration",
            "Sports Trends",
            "Work and Remote Work",
            "Others" ],
      Dream_Job : [ "Actor",
            "Athlete",
            "Baker",
            "Chef",
            "Dancer",
            "Doctor",
            "Entrepreneur",
            "Game Tester",
            "Illustrator",
            "Interior Designer",
            "Lawyer",
            "Model",
            "Musician",
            "Personal Trainer",
            "Pilot",
            "Police Officer",
            "Strengths",
            "Teacher",
            "Writer",
            "Zookeeper",
            "Others" ],
      Education : [ "College Accreditation",
            "Culturally Responsive Teaching",
            "Distance Learning",
            "Early Childhood Education",
            "Education Technology",
            "Educational Research",
            "Parent Involvement",
            "Pedagogical Methods and Innovations",
            "Reading and Literacy",
            "Special Education",
            "Standardized Testing",
            "Teacher Training and Educational Management",
            "Teaching",
            "Others" ],
      Family : [ "Blended Family",
            "Care for Elderly",
            "Cheating Spouse",
            "Childless Family",
            "Divorce",
            "Dual Career Family",
            "Extended Family",
            "Family Activity Ideas",
            "Family Life",
            "Immigration",
            "Loneliness",
            "Parenting",
            "Raising Responsible Kids",
            "Sibling Relationship",
            "Single Parent",
            "Work Life Balance",
            "Others" ],
      Food : [ "Breakfast",
            "Diet",
            "Diet Trends",
            "Dine-ins and Take-outs",
            "Drinks",
            "Fast Foods",
            "Favorite Food",
            "Food Addiction",
            "Health",
            "Losing and Gaining Weight",
            "Mindless Eating",
            "Non-vegetarian",
            "Pizza",
            "Restaurants",
            "Trying New Foods",
            "Vegan",
            "Vegetarian",
            "Others" ],
      Future : [ "10 Years from Now",
            "Childrens Future",
            "Future of Transportation",
            "Future of the Country",
            "Generation Gap",
            "Hopes and Dreams",
            "Man vs Machines",
            "Relationships and Future",
            "Saving for the Future",
            "Technology and Future",
            "Others" ],
      Goals : [ "Everyday Goals",
            "Failure",
            "Goal Setting",
            "Intermediate Goals",
            "Life Goals",
            "Manifestation",
            "Metrics and Charts",
            "Success",
            "Unrealistic Goals",
            "Vision Boards",
            "Others" ],
      Health : [ "Brain",
            "Childrens Health",
            "Diagnosis and Theraphy",
            "Disorders and Conditions",
            "Eyes and Vision",
            "Food and Nutrition",
            "Heart",
            "Immune System",
            "Injuries",
            "Kidneys",
            "Lungs",
            "Mental Health",
            "Sexual Health",
            "Skin and Hair and Nails",
            "Substance Use",
            "Teenagers and Health",
            "Teeth",
            "Wellness and Lifestyle",
            "Others" ],
      Hobbies :[ "Backpacking",
            "Biking",
            "Dancing",
            "Drawing",
            "Glassblowing",
            "Hiking",
            "Knitting",
            "Painting",
            "Photography",
            "Pottery",
            "Sewing",
            "Singing",
            "Video Games",
            "Writing",
            "Gardening",
            "Woodworking",
            "Others" ],
      Kids : [ "Baby Care",
            "Childrens Health",
            "Developmental Concerns",
            "Discipline",
            "Disrespect",
            "Habits",
            "Kids Education",
            "Kids Friendships",
            "Kids Safety",
            "Parenting Tips",
            "Relationship with Kids",
            "Social Anxiety in Kids",
            "Others" ],
      Manifestation : [ "Goal Setting",
            "Habit Breaking",
            "Habit Forming",
            "Inspired Action",
            "Law of Assumption",
            "Law of Attraction",
            "Limiting Beliefs",
            "Meditation",
            "Motivation",
            "SATS State Akin To Sleep",
            "The Secret",
            "Visualization",
            "Others" ],
      Music : [ "Concerts",
            "Does Music Rule the World",
            "Favorite Musical Genre",
            "Music Distracts or Helps",
            "Music Festivals",
            "Music and Technology",
            "Music that Inspires You",
            "Musicians",
            "Psychology of Music",
            "Types of Music Ensembles",
            "Unpopular Genres of Independent Music",
            "Using Music for Education",
            "Others" ],
      Personality_Development : [ "Assertiveness",
            "Communication",
            "Compassion",
            "Confidence",
            "Emotional Intelligence",
            "Goal Setting and Achievement",
            "Leadership",
            "Listen Actively",
            "Manage Stress",
            "Mindset",
            "Motivation",
            "Overcoming Fears",
            "Overcoming Procrastination",
            "Personal Development of Preschoolers",
            "Personal Growth",
            "Time Management",
            "Others" ],
      Science_And_Technology : [ "AI and Machine Learning",
            "Biotechnology and Genetic Engineering",
            "Blockchain and Cryptocurrencies",
            "Ethical and Social Implications",
            "IoT Internet of Things",
            "Nanotechnology",
            "Quantum Computing",
            "Renewable Energy",
            "Space Exploration",
            "Virtual Reality and Augmented Reality",
            "Others" ],
      Spirituality : [ "Agnosticism",
            "Atheism",
            "Cult",
            "Esotericism",
            "Ethics",
            "Extra-sensory Perception",
            "Faith",
            "Free Will",
            "Higher Consciousness",
            "Idealism",
            "Ietsism",
            "Karma",
            "Materialism",
            "Meditation",
            "Merkabah",
            "Metaphysics",
            "Mind-body Dualism",
            "Monotheism",
            "Mysticism",
            "Mythology",
            "Near-death Experience",
            "New Age",
            "Occultism",
            "Parapsychology",
            "Philosophy of Mind",
            "Philosophy of Religion",
            "Pseudoscience",
            "Psychiatry",
            "Psychology",
            "Reincarnation",
            "Skepticism",
            "Soul",
            "Subtle Body",
            "Superstition",
            "Truth",
            "Unconscious Mind",
            "Others" ],
      Sports : [ "Badminton",
            "Baseball",
            "Basketball",
            "Body Image",
            "Bowling",
            "Boxing",
            "Cricket",
            "Curling",
            "Football",
            "Golf",
            "Handball",
            "Health",
            "Hockey",
            "Karate",
            "Lacrosse",
            "Leadership",
            "Mental Wellness",
            "Nutrition and Hydration",
            "Skating",
            "Skiing",
            "Soccer",
            "Sportsmanship",
            "Swimming",
            "Table tennis",
            "Tennis",
            "Others" ],
      Travel :[ "Activities",
            "Blogging",    
            "Booking And Reservations",
            "Flights",
            "International Travel",
            "Places of Worship",
            "Tourism",
            "Travelling with kids",
            "Try Local Foods",
            "Vlogging",
            "Others" ]
   };

   let dropdown1 = document.getElementById(selectid);
   for (let i=0; i<dropdown1.options.length; i++)
   {
      topic = stringAddFiller(dropdown1.options[i].value);
      let subTopicDiv = document.getElementById(topic+'div');
      if (dropdown1.options[i].selected)
      {
         if (subTopicDiv || !optionsMap[topic])
            continue;
         let div = document.createElement("div");
         div.className = "selectfieldholder";
         div.id = topic + 'div';

         let p = document.createElement("p");
         p.id = topic + 'p' ;

         let label = document.createElement("label");
         label.className = "label-selectmultiple";
         label.innerText = dropdown1.options[i].value + " Topics I prefer to " +purpose+ "/Discuss";

         let select = document.createElement("select");
         select.id = topic;
         select.className ="selectmultiple";
         select.setAttribute('multiple', true);
         select.setAttribute('required', true);
         select.setAttribute('onchange', "updateP4DropDown('"+ topic +"')");
         let subtopics = optionsMap[topic];
         for (let i = 0; i < subtopics.length; i++)
         {
            let subtopicOption = document.createElement("option");
            subtopicOption.value = subtopics[i];
            subtopicOption.text = subtopics[i];
            select.appendChild(subtopicOption);
         }
         div.appendChild(select);
         div.appendChild(label);
         div.appendChild(p);
         document.body.appendChild (div);
      }
      else
      {
         if (subTopicDiv)
            document.body.removeChild(subTopicDiv);
      }
   }
}

// addOptions()
function addOptions ()
{ 
   let optionslist =
   {
      agegroup : [ "13-20",
            "21-30",
            "31-40",
            "41-50",
            "51-60",
            "61-70",
            "71 and older" ],
      language :[ "English",
            "Spanish",
            "French",
            "German",
            "Hindi",
            "Telugu",
            "Italian",
            "Tamil",
            "Malayalam" ],
      topics :[ 
            "Accomplishments",
            "Body Building",
            "Books",
            "Bucket List", 
            "Career Choices",
            "Clothes",
            "Cooking",
            "Current Trends",
            "Dream Job",
            "Education",
            "Embarrassing Moments",
            "Entertainment",
            "Family",
            "Food",
            "Future",
            "Goals",
            "Health",
            "Hobbies",
            "Kids",
            "Local Attractions",
            "Manifestation",
            "Meditation",
            "Movies",
            "Music",
            "Personality Development",
            "Politics",
            "Science And Technology",
            "Spirituality",
            "Sports",
            "Travel",
            ]
   };
   for (let selectid in optionslist)
   {
      let selectobj = document.getElementById(selectid);
      for (let i=0; i<optionslist[selectid].length; i++)
      {
         let option = document.createElement("option");
         option.value = optionslist[selectid][i];
         option.text = optionslist[selectid][i];
         selectobj.appendChild(option);
      }
   }
}
